version: '3.3'
services:

  uploader.postgres:
    image: postgres
    container_name: manager.postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
    - 7001:5432
    volumes:
    - "$HOME/docker/postgres:/var/lib/postgresql/data"
    - "$HOME/docker/postgres/postgres:/var/log/postgres"
    - "./config/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
    - "./config/postgres/postgresql.conf:/postgresql.conf"
    networks:
      default:
        aliases:
        - postgres

  uploader.redis:
    image: redis:alpine
    container_name: manager.redis
    ports:
    - 7100:6379
    volumes:
    - "$HOME/docker/redis/redis:/var/log/redis"
    - "./config/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    networks:
      default:
        aliases:
        - redis

  uploader.rabbitmq:
    image: rabbitmq:3.7.7-management
    container_name: manager.rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: local
      RABBITMQ_DEFAULT_USER:  root
      RABBITMQ_DEFAULT_PASS:  password
    volumes:
    - "$HOME/docker/rabbitmq:/var/lib/rabbitmq:rw"
    ports:
    - 15673:15672
    - 5673:5672
    networks:
      default:
        aliases:
        - rabbitmq

volumes:
  esdata1:
    driver: local
